# Generated by Django 4.0.4 on 2022-06-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistrarRem', '0002_alter_acompanante_apellidop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='apellidoP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='apellidoS',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='direccionHabitual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección de residencia'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado afiliación'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='fechaNacimiento',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='ipsPrimaria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IPS primaria'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='municipioHabitual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Municipio de residencia'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='nombreP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='nombreS',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='numIdentificacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número identificación'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='regimen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Régimen'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='tipoIdentificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appRegistrarRem.tipoidentificacion'),
        ),
    ]
