# Generated by Django 4.0.4 on 2022-06-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistrarRem', '0003_alter_afiliado_apellidop_alter_afiliado_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='direccionHabitual',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='ipsPrimaria',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='municipioHabitual',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='regimen',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='telefono',
        ),
    ]
